# Generated by Django 3.2.7 on 2021-09-26 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Crypto',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=3, max_digits=20)),
                ('changement', models.DecimalField(decimal_places=3, max_digits=20)),
                ('volume', models.DecimalField(decimal_places=3, max_digits=20)),
                ('market', models.DecimalField(decimal_places=3, max_digits=20)),
            ],
        ),
    ]
