# Generated by Django 3.2.7 on 2021-09-26 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getCrypto', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crypto',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
